config/routes.rb
Rails.application.routes.draw do
  resources :messages

  get 'login' => 'user_sessions#new', :as => :login
  post 'logout' => 'user_sessions#destroy', :as => :logout
  
  resources :user_sessions
  
  resources :loans
  
  resources :items
  
  resources :users
  
  resources :charges
  
  get 'loans/:id/approve' => "loans#approve"
  
  root :to => "home#index", :as => :home
  
  get 'search' => "items#search", :as => :search
  
  get ':id' => "users#show", :as => :profile
  
  get ':id/edit' => "users#edit"
  
  get 'last' => "home#last"

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def last
  end
  
  def index    
    if current_user
      
      @in_my_house = Loan.where(borrower_id: current_user.id, approved: true)
      @in_their_house = Loan.where(loaner_id: current_user.id, approved: true)
      @pending = Loan.where(loaner_id: current_user.id, approved: nil)
      @pending_borrows = Loan.where(borrower_id: current_user.id, approved: nil)
  
      @items_in_my_house = []
  
      @in_my_house.each do |loan|
        @item = Item.find(loan.item_id)
        @items_in_my_house << @item
      end
      
      @items_in_their_house = []
  
      @in_their_house.each do |loan|
        @item = Item.find(loan.item_id)
        @items_in_their_house << @item
      end
      
      @items_pending = []
  
      @pending.each do |loan|
        @item = Item.find(loan.item_id)
        @items_pending << @item
      end
      
      @borrows_pending = []
  
      @pending_borrows.each do |loan|
        @item = Item.find(loan.item_id)
        @borrows_pending << @item
      end
  
      @on_my_porch = Item.where(user_id: current_user.id) - @items_pending - @items_in_their_house
  
      @items = Item.all - @on_my_porch - @items_pending - @items_in_my_house - @items_in_their_house - @borrows_pending
      
      @distances = []
      
      @community_items = []
      
      @items.each do |item|
        a = Geokit::Geocoders::GoogleGeocoder.geocode "#{current_user.address} #{current_user.city} #{current_user.state} #{current_user.zip}"
        b = Geokit::Geocoders::GoogleGeocoder.geocode "#{item.user.address} #{item.user.city} #{item.user.state} #{item.user.zip}"
        if a.distance_to(b) < 10
          @community_items << item
        end
      end
      
    else
      if request.ip == "127.0.0.1"
        @location_ll = "43.5540953,-96.7280335"
      else
        @location = request.location
        @location_ll = @location.latitude + @location.longitude
      end
      
      @borrowed = Loan.where(approved: true)
  
      @items_borrowed = []
  
      @borrowed.each do |loan|
        @item = Item.find(loan.item_id)
        @items_borrowed << @item
      end
      
      @items = Item.all - @items_borrowed
      
      @distances = []
      
      @community_items = []
      
      @items.each do |item|
        a = Geokit::Geocoders::GoogleGeocoder.geocode "#{@location_ll}"
        b = Geokit::Geocoders::GoogleGeocoder.geocode "#{item.user.address} #{item.user.city} #{item.user.state} #{item.user.zip}"
        if a.distance_to(b) < 10
          @community_items << item
        end
      end
    end
  end
end

app/views/home/_landing_page.html.erb
<div class="hero">
    <div class="content">
        <h1>THE LIBRARY FOR EVERYTHING</h1>
        <%= form_tag items_path, :method => :get, :class => "search-wrapper", :id => "new_item" do %>
          <p class="search--home">
            <%= text_field_tag :search, params[:search], :id => "home_search", :placeholder => "SEARCH FOR THINGS TO BORROW." %>
            <%= submit_tag "", :name => nil %>
          </p>
        <% end %>
    </div>
</div>
<div class="how--it--works">
    <div class="content">
        <div class="home--header">
          <div class="home--header--left">
              <div class="home--header--long">
              </div>
              <div class="home--header--short">
              </div>
          </div>
          <h2>HOW IT WORKS</h2>
          <div class="home--header--right">
              <div class="home--header--long">
              </div>
              <div class="home--header--short">
              </div>
          </div>
        </div>
        <div class="how--it--works--container">
            <div class="how--it--works--section">
                <div class="how--it--works--graphic">
                    <%= image_tag("drill_2x.png", :alt => "drill") %>
                </div>
                <div class="how--it--works--text">
                    <h3>List items<br/> available to rent</h3>
                </div>
            </div>
            <div class="how--it--works--section">
                <div class="how--it--works--graphic">
                    <%= image_tag("available-items_2x.png", :alt => "available items") %>
                </div>
                <div class="how--it--works--text">
                    <h3>Find available<br/> items nearby</h3>
                </div>
            </div>
            <div class="how--it--works--section">
                <div class="how--it--works--graphic">
                    <%= image_tag("home_2x.png", :alt => "home") %>
                </div>
                <div class="how--it--works--text">
                    <h3>Pick up</h3>
                </div>
            </div>
            <div class="how--it--works--section">
                <div class="how--it--works--graphic">
                    <%= image_tag("parachute_2x.png", :alt => "parachute") %>
                </div>
                <div class="how--it--works--text">
                    <h3>Return in two days</h3>
                </div>
            </div>
            <div class="how--it--works--section">
                <div class="how--it--works--graphic">
                    <%= image_tag("money_2x.png", :alt => "money") %>
                </div>
                <div class="how--it--works--text">
                    <h3>Make money.<br/> Save money.</h3>
                </div>
            </div>
        </div>
    </div>
</div>
<% if @community_items != false %>
    <div class="nearby--listings">
        <div class="content">
        <% if @community_items.count != 0 %>
        <div class="home--header">
            <div class="home--header--left">
                <div class="home--header--long">
                </div>
                <div class="home--header--short">
                </div>
            </div>
            <h2>NEARBY LISTINGS</h2>
            <div class="home--header--right">
                <div class="home--header--long">
                </div>
                <div class="home--header--short">
                </div>
            </div>
        </div>
        <% end %>
        <div class="items">
        <% @community_items.each do |item| %>
              <div class="item">
                  <%= link_to item_path(item) do %>
                      <div class="item--photo" style="background:url('<%= item.photo %>'); background-size: cover;">
                      </div>
                  <% end %>

                  <div class="user--info index">
                      <%= link_to user_path(item.user) do %>
                          <div class="square">
                              <div class="pic" style="background: url(<%= item.user.photo.thumb %>); background-size: 100%; background-position: center center; background-repeat: no-repeat;">
                              </div>
                          </div>
                      <% end %>

                      <div class="username">
                          <%= link_to "#{item.user.first_name}", item.user %>
                      </div>
                  </div>

                  <div class="item--name">
                      <%= link_to "#{item.name}", item %>
                  </div>

                  <%= link_to item_path(item) do %>
                      <div class="price">
                          <%= "$#{'%.0f' % item.price}" %>
                          <%= image_tag("arrow.png", class: "arrow") %>
                      </div>
                  <% end %>
              </div>
          <% end %>
          <% if @community_items.count % 3 == 1 || @community_items.count == 2 || @community_items.count % 3 == 2 %>
            <div class="item">
            </div>
          <% end %>
          </div>
      </div>
    </div>
<% else %>
    <div class="nearby--listings">
        <div class="content">
            <div class="home--header">
                <div class="home--header--left">
                    <div class="home--header--long">
                    </div>
                    <div class="home--header--short">
                    </div>
                </div>
                <h2>NEARBY LISTINGS</h2>
                <div class="home--header--right">
                    <div class="home--header--long">
                    </div>
                    <div class="home--header--short">
                    </div>
                </div>
            </div>
            <p>Enter your address to see items listed nearby.</p>
            <%= form_tag "/", :method => :get do %>
                <p>
                    <%= text_field_tag :address, params[:address], :placeholder => "address" %>
                    <%= text_field_tag :city, params[:city], :placeholder => "city" %>
                    <%= text_field_tag :state, params[:state], :placeholder => "state" %>
                    <%= text_field_tag :zip, params[:zip], :placeholder => "zip" %>
                    <%= submit_tag "see listings", :id => "submit", :name => nil %>
                </p>
            <% end %>
        </div>
    </div>
<% end %>

app/views/home/_logged_in.html.erb
<div class="search-wrapper">
<%= form_tag items_path, :method => :get do %>
  <p>
    <%= text_field_tag :search, params[:search], :placeholder => "SEARCH FOR THINGS TO BORROW." %>
    <%= submit_tag "", :id => "submit", :name => nil %>
  </p>
<% end %>
</div>

<div class="container">
  
  <div class="tabs--container">
  	<ul class="tabs">
  		<li class="tab-link current" data-tab="tab-1">ON MY PORCH (<%= @on_my_porch.count + @items_pending.count %>)</li>
      <% if @in_my_house.count != 0 || nil %>
  		<li class="tab-link" data-tab="tab-2">IN MY HOUSE (<%= @in_my_house.count %>)</li>
      <% end %>
      <% if @in_their_house.count != 0 || nil %>
  		<li class="tab-link" data-tab="tab-3">IN THEIR HOUSE (<%= @in_their_house.count %>)</li>
      <% end %>
  	</ul>
  </div>
  
  <section class="tabs-section--container">
  	<div id="tab-1" class="tab-content current">
      <% if @on_my_porch != nil || [] %>
        <h1>Your items ready to loan out</h1>
        <div class="tab--items">
        <% if @items_pending != nil || [] %>
        <% @items_pending.each do |item| %>
          <div class="tab--item">
            <%= link_to item_path(item) do %>
                <div class="item--photo" style="background:url('<%= item.photo %>'); background-size: cover;">
                </div>
            <% end %>
            <div class="bottom--section">
              <div class="tab--name"><h2><%= link_to "#{item.name}", item %></h2></div>
              <div class="top--buttons">
                <div class="edit"><%= link_to(image_tag("icons/edit.png", :alt => "edit"), edit_item_path(item)) %></div>
                <div class="calendar"><%= link_to(image_tag("icons/calendar.png", :alt => "calendar"), item) %></div>
              </div>
            </div>
            <div class="item--bottom">
            <div class="price">Loan to <%= link_to((User.find(item.loans.last.borrower_id).first_name), user_path(User.find(item.loans.last.borrower_id).id)) %></a>?</div>
              <div class="trash"><%= link_to(image_tag("icons/approve.png", :alt => "approve"), "/loans/#{item.loans.last.id}/approve", data: { confirm: 'Are you sure you want to approve this loan?' }) %></div>
            </div>
          </div>
        <% end %>
      <% end %>
      <% @on_my_porch.each do |item| %>
            <div class="tab--item">
                <%= link_to item_path(item) do %>
                    <div class="item--photo" style="background:url('<%= item.photo %>'); background-size: cover;">
                    </div>
                <% end %>
                <div class="bottom--section">
                    <div class="tab--name"><h2><%= link_to "#{item.name}", item %></h2></div>
                    <div class="top--buttons">
                        <div class="edit"><%= link_to(image_tag("icons/edit.png", :alt => "edit"), edit_item_path(item)) %></div>
                        <div class="calendar"><%= link_to(image_tag("icons/calendar.png", :alt => "calendar"), item) %></div>
                    </div>
                </div>
                <div class="item--bottom">
                    <div class="price">$<%= '%.0f' % item.price %></div>
                    <div class="trash"><%= link_to(image_tag("icons/trash.png", :alt => "trash"), item_path(item), method: :delete, data: { confirm: 'Are you sure you want to delete this?' }) %></div>
                </div>
            </div>
      <% end %>
      <div class="tab--item">
            <a href="items/new">
                <div class="item--photo" style="background:url('assets/new-item_2x.png')">
                </div>
            </a>
            <div class="bottom--section">
                <div class="tab--name"><h2><a href="items/new">New Item</a></h2></div>
                <div class="top--buttons">
                    <div class="edit"><%= image_tag("icons/edit.png", :alt => "edit") %></div>
                    <div class="calendar"><%= image_tag("icons/calendar.png", :alt => "calendar") %></div>
                </div>
            </div>
            <div class="item--bottom">
                <div class="price">$0</div>
                <div class="trash"><%= image_tag("icons/trash.png", :alt => "trash") %></div>
            </div>
      </div>
      <% if (@on_my_porch.count + @items_pending.count) % 3 == 1 || (@on_my_porch.count + @items_pending.count) == 2 %>
        <div class="tab--item">
        </div>
      <% end %>
      </div>
      <% end %>
  	</div>
  	<div id="tab-2" class="tab-content">
      <h1>Their items you're borrowing</h1>
      <div class="tab--items">
      <% @in_my_house.each do |loan| %>
        <div class="tab--item">
          <%= link_to item_path(loan.item) do %>
              <div class="item--photo" style="background:url('<%= loan.item.photo %>'); background-size: cover;">
              </div>
          <% end %>
          <div class="bottom--section">
            <div class="tab--name"><h2><%= link_to "#{loan.item.name}", loan.item %></h2></div>
            <div class="top--buttons">
              <div class="edit"><%= link_to(image_tag("icons/edit.png", :alt => "edit"), edit_item_path(loan.item)) %></div>
              <div class="calendar"><%= link_to(image_tag("icons/calendar.png", :alt => "calendar"), loan.item) %></div>
            </div>
          </div>
          <div class="item--bottom">
          <div class="price">$<%= '%.0f' % loan.item.price %></div>
            <div class="trash"><%= link_to(image_tag("icons/trash.png", :alt => "trash"), item_path(loan.item), method: :delete, data: { confirm: 'Are you sure you want to delete this?' }) %></div>
          </div>
        </div>
      <% end %>
      <% if @in_my_house.count == @in_my_house.count % 3 + 1 || 2 %>
        <div class="tab--item">
        </div>
      <% end %>
      </div>
  	</div>
  	<div id="tab-3" class="tab-content">
      <h1>Your items others are borrowing</h1>
      <div class="tab--items">
      <% @in_their_house.each do |loan| %>
        <div class="tab--item">
          <%= link_to item_path(loan.item) do %>
              <div class="item--photo" style="background:url('<%= loan.item.photo %>')">
              </div>
          <% end %>
          <div class="bottom--section">
            <div class="tab--name"><h2><%= link_to "#{loan.item.name}", loan.item %></h2></div>
            <div class="top--buttons">
              <div class="edit"><%= link_to(image_tag("icons/edit.png", :alt => "edit"), edit_item_path(loan.item)) %></div>
              <div class="calendar"><%= link_to(image_tag("icons/calendar.png", :alt => "calendar"), loan.item) %></div>
            </div>
          </div>
          <div class="item--bottom">
          <div class="price">$<%= '%.0f' % loan.item.price %></div>
            <div class="trash"><%= link_to(image_tag("icons/trash.png", :alt => "trash"), item_path(loan.item), method: :delete, data: { confirm: 'Are you sure you want to delete this?' }) %></div>
          </div>
        </div>
      <% end %>
      </div>
  	</div>
  </section>
</div>

<% if @community_items.count != nil || 0 %>
<div class="nearby--listings">
    <div class="home--header">
      <div class="home--header--left">
          <div class="home--header--long">
          </div>
          <div class="home--header--short">
          </div>
      </div>
      <h2>NEARBY LISTINGS</h2>
      <div class="home--header--right">
          <div class="home--header--long">
          </div>
          <div class="home--header--short">
          </div>
      </div>
    </div>
    <div class="items">
    <% @community_items.each do |item| %>
          <div class="item">
             <%= link_to item_path(item) do %>
                  <div class="item--photo" style="background:url('<%= item.photo %>'); background-size: cover;">
                  </div>
             <% end %>
  
              <div class="user--info index">
                  <a href="users/<%= item.user.id %>">
                      <div class="square">
                          <div class="pic" style="background: url(<%= item.user.photo %>); background-size: 100%; background-position: center center; background-repeat: no-repeat;">
                          </div>
                      </div>
                  </a>
  
                  <div class="username">
                      <%= link_to "#{item.user.first_name}", item.user %>
                  </div>
              </div>
  
              <div class="item--name">
                  <%= link_to "#{item.name}", item %>
              </div>
    
              <%= link_to item_path(item) do %>
                  <div class="price">
                      <%= "$#{'%.0f' % item.price}" %>
                      <%= image_tag("arrow.png", class: "arrow") %>
                  </div>
              <% end %>
          </div>
      <% end %>
      <% if @community_items.count % 3 == 1 || @community_items.count == 2 || @community_items.count % 3 == 2 %>
        <div class="item">
        </div>
      <% end %>
      </div>
</div>
<% end %>

app/views/home/_logged_in_two.html.erb
<div class="search-wrapper">
    <%= form_tag items_path, :method => :get do %>
        <p>
            <%= text_field_tag :search, params[:search], :placeholder => "SEARCH FOR THINGS TO BORROW." %>
            <%= submit_tag "", :id => "submit", :name => nil %>
        </p>
    <% end %>
</div>

<section class="landing-page">
    <section class="landing-page--items">
        <dl class="accordion">
            <% if @borrows_pending.count != 0 || nil %>
            <dt class="accordion__title">Your Requests (<%= @borrows_pending.count %>)</dt>
            <dd class="accordion__content">
                <div class="tab--items">
                <% @borrows_pending.each do |item| %>
                    <div class="tab--item">
                    <%= link_to item_path(item) do %>
                        <div class="item--photo" style="background:url('<%= item.photo %>'); background-size: cover;">
                        </div>
                    <% end %>
                    <div class="bottom--section">
                        <div class="tab--name">
                            <h2><%= link_to "#{item.name}", item %></h2>
                        </div>
                        <div class="top--buttons">
                            <div class="edit">
                                <%= link_to(image_tag("icons/edit.png", :alt => "edit"), edit_item_path(item)) %>
                            </div>
                            <div class="calendar">
                                <%= link_to(image_tag("icons/calendar.png", :alt => "calendar"), item) %>
                            </div>
                        </div>
                    </div>
                    <div class="item--bottom">
                        <div class="price">$<%= '%.0f' % item.price %></div>
                        <div class="trash"><%= link_to(image_tag("icons/trash.png", :alt => "trash"), item_path(item), method: :delete, data: { confirm: 'Are you sure you want to delete this?' }) %></div>
                        </div>
                    </div>
                <% end %>
                <% if @borrows_pending.count == @borrows_pending.count % 3 + 1 || 2 %>
                    <div class="tab--item">
                    </div>
                <% end %>
                </div>
                
            </dd>
            <% end %>
            <% if @items_pending.count != 0 || nil %>
            <dt class="accordion__title">Their Requests (<%= @items_pending.count %>)</dt>
            <dd class="accordion__content">
                <div class="tab--items">
                <% @items_pending.each do |item| %>
                    <div class="tab--item">
                    <%= link_to item_path(item) do %>
                        <div class="item--photo" style="background:url('<%= item.photo %>'); background-size: cover;">
                        </div>
                    <% end %>
                    <div class="bottom--section">
                        <div class="tab--name">
                            <h2><%= link_to "#{item.name}", item %></h2>
                        </div>
                        <div class="top--buttons">
                            <div class="edit">
                                <%= link_to(image_tag("icons/edit.png", :alt => "edit"), edit_item_path(item)) %>
                            </div>
                            <div class="calendar">
                                <%= link_to(image_tag("icons/calendar.png", :alt => "calendar"), item) %>
                            </div>
                        </div>
                    </div>
                    <div class="item--bottom">
                        <div class="price">$<%= '%.0f' % item.price %></div>
                        <div class="trash"><%= link_to(image_tag("icons/approve.png", :alt => "approve"), "/loans/#{item.loans.last.id}/approve", data: { confirm: 'Are you sure you want to approve this loan?' }) %></div>
                        </div>
                    </div>
                <% end %>
                <% if @items_pending.count == @items_pending.count % 3 + 1 || 2 %>
                    <div class="tab--item">
                    </div>
                <% end %>
                </div>
                
            </dd>
            <% end %>
            <% if @in_their_house.count != 0 || nil %>
            <dt class="accordion__title">Loans (<%= @in_their_house.count %>)</dt>
            <dd class="accordion__content">
                <div class="tab--items">
                <% @in_their_house.each do |loan| %>
                    <div class="tab--item">
                    <%= link_to item_path(loan.item) do %>
                        <div class="item--photo" style="background:url('<%= loan.item.photo %>'); background-size: cover;">
                        </div>
                    <% end %>
                    <div class="bottom--section">
                        <div class="tab--name">
                            <h2><%= link_to "#{loan.item.name}", loan.item %></h2>
                        </div>
                        <div class="top--buttons">
                            <div class="edit">
                                <%= link_to(image_tag("icons/edit.png", :alt => "edit"), edit_item_path(loan.item)) %>
                            </div>
                            <div class="calendar">
                                <%= link_to(image_tag("icons/calendar.png", :alt => "calendar"), loan.item) %>
                            </div>
                        </div>
                    </div>
                    <div class="item--bottom">
                        <div class="price">$<%= '%.0f' % loan.item.price %></div>
                        <div class="trash"><%= link_to(image_tag("icons/trash.png", :alt => "trash"), item_path(loan.item), method: :delete, data: { confirm: 'Are you sure you want to delete this?' }) %></div>
                        </div>
                    </div>
                <% end %>
                <% if @in_their_house.count == @in_their_house.count % 3 + 1 || 2 %>
                    <div class="tab--item">
                    </div>
                <% end %>
                </div>
                
            </dd>
            <% end %>
            <% if @in_my_house.count != 0 || nil %>
            <dt class="accordion__title">Borrows (<%= @in_my_house.count %>)</dt>
            <dd class="accordion__content">
                <div class="tab--items">
                <% @in_my_house.each do |loan| %>
                    <div class="tab--item">
                    <%= link_to item_path(loan.item) do %>
                        <div class="item--photo" style="background:url('<%= loan.item.photo %>'); background-size: cover;">
                        </div>
                    <% end %>
                    <div class="bottom--section">
                        <div class="tab--name">
                            <h2><%= link_to "#{loan.item.name}", loan.item %></h2>
                        </div>
                        <div class="top--buttons">
                            <div class="edit">
                                <%= link_to(image_tag("icons/edit.png", :alt => "edit"), edit_item_path(loan.item)) %>
                            </div>
                            <div class="calendar">
                                <%= link_to(image_tag("icons/calendar.png", :alt => "calendar"), loan.item) %>
                            </div>
                        </div>
                    </div>
                    <div class="item--bottom">
                        <div class="price">$<%= '%.0f' % loan.item.price %></div>
                        <div class="trash"><%= link_to(image_tag("icons/trash.png", :alt => "trash"), item_path(loan.item), method: :delete, data: { confirm: 'Are you sure you want to delete this?' }) %></div>
                        </div>
                    </div>
                <% end %>
                <% if @in_my_house.count == @in_my_house.count % 3 + 1 || 2 %>
                    <div class="tab--item">
                    </div>
                <% end %>
                </div>
                
            </dd>
            <% end %>
            <% if @on_my_porch.count != 0 || nil %>
            <dt class="accordion__title">Inventory (<%= @on_my_porch.count %>)</dt>
            <dd class="accordion__content">
                <div class="tab--items">
                <% @on_my_porch.each do |item| %>
                    <div class="tab--item">
                    <%= link_to item_path(item) do %>
                        <div class="item--photo" style="background:url('<%= item.photo %>'); background-size: cover;">
                        </div>
                    <% end %>
                    <div class="bottom--section">
                        <div class="tab--name">
                            <h2><%= link_to "#{item.name}", item %></h2>
                        </div>
                        <div class="top--buttons">
                            <div class="edit">
                                <%= link_to(image_tag("icons/edit.png", :alt => "edit"), edit_item_path(item)) %>
                            </div>
                            <div class="calendar">
                                <%= link_to(image_tag("icons/calendar.png", :alt => "calendar"), item) %>
                            </div>
                        </div>
                    </div>
                    <div class="item--bottom">
                        <div class="price">$<%= '%.0f' % item.price %></div>
                        <div class="trash"><%= link_to(image_tag("icons/trash.png", :alt => "trash"), item_path(item), method: :delete, data: { confirm: 'Are you sure you want to delete this?' }) %></div>
                        </div>
                    </div>
                <% end %>
                <% if @on_my_porch.count == @on_my_porch.count % 3 + 1 || 2 %>
                    <div class="tab--item">
                    </div>
                <% end %>
                </div>
            </dd>
            <% end %>
            <dt class="add-item"><a href="items/new">Add An Item</a></dt>
        </dl>
    </section>
    <% if @community_items.count != nil || 0 %>
    <div class="nearby--listings">
        <div class="home--header">
          <div class="home--header--left">
              <div class="home--header--long">
              </div>
              <div class="home--header--short">
              </div>
          </div>
          <h2>NEARBY LISTINGS</h2>
          <div class="home--header--right">
              <div class="home--header--long">
              </div>
              <div class="home--header--short">
              </div>
          </div>
        </div>
        <div class="items">
        <% @community_items.each do |item| %>
              <div class="item">
                 <%= link_to item_path(item) do %>
                      <div class="item--photo" style="background:url('<%= item.photo %>'); background-size: cover;">
                      </div>
                 <% end %>

                  <div class="user--info index">
                      
                      <%= link_to item.user do %>
                          <div class="square">
                              <div class="pic" style="background: url(<%= item.user.photo.thumb %>); background-size: 100%; background-position: center center; background-repeat: no-repeat;">
                              </div>
                          </div>
                      <% end %>

                      <div class="username">
                          <%= link_to "#{item.user.first_name}", item.user %>
                      </div>
                  </div>

                  <div class="item--name">
                      <%= link_to "#{item.name}", item %>
                  </div>

                  <%= link_to item_path(item) do %>
                      <div class="price">
                          <%= "$#{'%.0f' % item.price}" %>
                          <%= image_tag("arrow.png", class: "arrow") %>
                      </div>
                  <% end %>
              </div>
          <% end %>
          <% if @community_items.count % 3 == 1 || @community_items.count == 2 || @community_items.count % 3 == 2 %>
            <div class="item">
            </div>
          <% end %>
          </div>
    </div>
    <% end %>
</section>

<script>
    if ($(window).width() > 768) {
        $('.accordion__content:not(:first)').hide();

        $('.accordion__title:first-child').addClass('active');
    } else {
        $('.accordion__content').hide();
    };

    $( ".accordion__content" ).wrapInner( "<div class='overflow-scrolling'></div>" );

    $('.accordion__title').on('click', function() {
        $('.accordion__content').hide();
        $(this).next().show().prev().addClass('active').siblings().removeClass('active');
    });
</script>

app/views/home/index.html.erb
<% if current_user %>
    <%= render 'logged_in_two' %>
<% else %>
    <%= render 'landing_page' %>
<% end %>

app/views/home/last.html.erb
<%= image_tag("last.png") %>