config/routes.rb
Rails.application.routes.draw do
  resources :messages

  get 'login' => 'user_sessions#new', :as => :login
  post 'logout' => 'user_sessions#destroy', :as => :logout
  
  resources :user_sessions
  
  resources :loans
  
  resources :items
  
  resources :users
  
  resources :charges
  
  get 'loans/:id/approve' => "loans#approve"
  
  root :to => "home#index", :as => :home
  
  get 'search' => "items#search", :as => :search
  
  get ':id' => "users#show", :as => :profile
  
  get ':id/edit' => "users#edit"
  
  get 'last' => "home#last"

end

app/models/loan.rb
class Loan < ActiveRecord::Base
  belongs_to :item
  belongs_to :loaner, :class_name => "User"
  belongs_to :borrower, :class_name => "User"
  belongs_to :charges
  has_many :messages
  
  attr_accessor :stripe_card_token

  def save_with_payment

    if valid?
      
      if self.borrower.stripe_customer_token.present? && self.borrower.stripe_customer_token != 0
        
        self.stripe_customer_token = self.borrower.stripe_customer_token
        
        if self.borrower.stripe_recipient_id.present? == false || self.borrower.stripe_recipient_id == 0
          
          recipient = Stripe::Recipient.create(
            :name => self.borrower.first_name + " " + self.borrower.last_name,
            :type => "individual",
            :email => self.borrower.email,
            :card => stripe_card_token
          )
          self.borrower.update_attribute(:stripe_recipient_id, recipient.id)
        end
        
      else
        
        customer = Stripe::Customer.create(
          card: stripe_card_token, 
          email: email
        )
        
        self.stripe_customer_token = customer.id
        self.borrower.update_attribute(:stripe_customer_token, customer.id)
        
      end
      save!
    end
    
    rescue Stripe::InvalidRequestError => e
      logger.error "Stripe error while creating customer: #{e.message}"
      errors.add :base, "There was a problem with your credit card."
      false
  end
end

app/controllers/loans_controller.rb
class LoansController < ApplicationController
  before_action :set_loan, only: [:show, :edit, :approve, :update, :destroy]

  # GET /loans
  # GET /loans.json
  def index
    @loans = Loan.where(loaner_id: current_user.id)
    @rentals = Loan.where(borrower_id: current_user.id)
  end

  # GET /loans/1
  # GET /loans/1.json
  def show
  end

  # GET /loans/new
  def new
    @loan = Loan.new
  end

  # GET /loans/1/edit
  def edit
  end
  
  def approve
    customer_id = @loan.borrower.stripe_customer_token

    Stripe::Charge.create(
      :amount => @loan.item.price.to_i * 100,
      :currency => "usd",
      :customer => customer_id,
      :description => "Due in Two: #{@loan.item.name} borrow from @#{@loan.loaner.username}."
    )
    
    @owner_profit = (((@loan.item.price.to_i * 100) - 30) * 0.95).round

    Stripe::Transfer.create(
       :amount => @owner_profit,
       :currency => "usd",
       :recipient => @loan.loaner.stripe_recipient_id,
       :description => "Due in Two: #{@loan.item.name} loan to @#{@loan.borrower.username}."
    )
    
    respond_to do |format|  ## Add this
      if @loan.update(approved: true)
        format.html { redirect_to "/", notice: 'Loan was approved.' }
        format.json { render :show, status: :ok, location: @loan }
      else
        format.html { redirect_to "/", notice: '#{@loan.errors}' }
        format.json { render json: @loan.errors, status: :unprocessable_entity }
      end
    end
  end

  # POST /loans
  # POST /loans.json
  def create
    @loan = Loan.new(loan_params)
    
    respond_to do |format|
      if @loan.save_with_payment
        @loan.update(reserved_start: Date.parse(Date.strptime(loan_params[:reserved_start],'%m/%d/%Y').strftime("%Y-%m-%d")) )
        @loan.update(reserved_end: @loan.reserved_start + 2.days)
        format.html { redirect_to @loan.item }
        format.json { render :show, status: :created, location: @loan }
      else
        format.html { render :new, notice: '#{@loan.errors}' }
        format.json { render json: @loan.errors, status: :unprocessable_entity }
      end 
    end
  end

  # PATCH/PUT /loans/1
  # PATCH/PUT /loans/1.json
  def update
    respond_to do |format|
      if @loan.update(loan_params) && @loan.update(reserved_end: @loan.reserved_start + 2.days)
        format.html { redirect_to @loan, notice: 'Loan was successfully updated.' }
        format.json { render :show, status: :ok, location: @loan }
      else
        format.html { render :edit }
        format.json { render json: @loan.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /loans/1
  # DELETE /loans/1.json
  def destroy
    @loan.destroy
    respond_to do |format|
      format.html { redirect_to loans_url, notice: 'Loan was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_loan
      @loan = Loan.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def loan_params
      params.require(:loan).permit(:item_id, :borrower_id, :loaner_id, :approved, :reserved_start, :reserved_end, :stripe_customer_token, :stripe_card_token, :email)
    end
end

app/helpers/loans_helper.rb
module LoansHelper
end

app/views/loans/_form.html.erb
<%= form_for(@loan) do |f| %>
  <% if @loan.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@loan.errors.count, "error") %> prohibited this loan from being saved:</h2>

      <ul>
      <% @loan.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :item_id %><br>
    <%= f.collection_select :item_id, Item.all, :id, :name %>
  </div>
  <%= f.hidden_field :borrower_id, :value => current_user.id%>
  <%= f.hidden_field :loaner_id, :value => current_user.id%>
  <div class="field">
    <%= f.label :loaner_id %><br>
    <%= f.collection_select :loaner_id, User.all, :id, :username %>
  </div>
  <div class="field">
    <%= f.label :loaner_id %><br>
    <%= f.number_field :loaner_id %>
  </div>
  <div class="field">
    <%= f.label :approved %><br>
    <%= f.check_box :approved %>
  </div>
  <div class="field">
    <%= f.label :reserved_start %><br>
    <%= f.datetime_select :reserved_start %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/loans/edit.html.erb
<h1>Editing loan</h1>

<%= form_for(@loan) do |f| %>
  <% if @loan.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@loan.errors.count, "error") %> prohibited this loan from being saved:</h2>

      <ul>
      <% @loan.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :reserved_start %><br>
    <%= f.datetime_select :reserved_start %>
  </div>
  <% if current_user.id == @loan.loaner_id %>
  <div class="field">
    <%= f.label :approved %><br>
    <%= f.check_box :approved %>
  </div>
  <% end %>
  <div class="actions">
    <% if current_user.id == @loan.loaner_id %>
    <%= f.submit "Update" %>
    <% else %>
    <%= f.submit "Update pickup time" %>
    <% end %>
  </div>
<% end %>


<%= link_to 'Show', @loan %> |
<%= link_to 'Back', loans_path %>

app/views/loans/index.html.erb
<a href="/last">
<%= image_tag("screen.png") %>
</a>

<!-- <div class="loan--approval">

<p id="notice"><%= notice %></p>

<h1>Loan approval</h1>

<% @loans.each do |loan| %>
  <%= User.find(loan.borrower_id).username %>'s rental of your <%= loan.item.name %>
  <% if loan.approved == true %>
    is approved.
    <h3>Pickup time</h3>
    <%= loan.reserved_start.strftime("%B %d at %I:%M %p") %>
    <h3>Dropoff day</h3>
    <%= loan.reserved_end.strftime("%B %d") %>
  <% elsif loan.approved == false %>
    was denied.
  <% else %>
    is pending.
    <h3>Their proposed pickup time</h3>
    <%= loan.reserved_start.strftime("%B %d at %I:%M %p") %>
    <%= link_to 'Edit', edit_loan_path(loan) %>
    <%= link_to 'Approve', "/loans/#{loan.id}/approve" %>
    <h3>Dropoff day</h3>
    <%= loan.reserved_end.strftime("%B %d") %>
  <% end %>
<% end %>

<h1>Rental approval</h1>

<% @rentals.each do |loan| %>
  Your rental of <%= User.find(loan.loaner_id).username %>'s <%= loan.item.name %>
  <% if loan.approved == true %>
    is approved.
    <h3>Pickup time</h3>
    <%= loan.reserved_start.strftime("%B %d at %I:%M %p") %>
    <h3>Dropoff day</h3>
    <%= loan.reserved_end.strftime("%B %d") %>
  <% elsif loan.approved == false %>
    was denied.
  <% else %>
    is pending.
    <h3>Your proposed pickup time</h3>
    <%= loan.reserved_start.strftime("%B %d at %I:%M %p") %>
    <%= link_to 'Edit pickup time', edit_loan_path(loan) %>
    <h3>Dropoff day</h3>
    <%= loan.reserved_end.strftime("%B %d") %>
  <% end %>
<% end %>

</div> -->

app/views/loans/new.html.erb
<h1>New loan</h1>

<%= render 'form' %>

<%= link_to 'Back', loans_path %>

app/views/loans/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Item:</strong>
  <%= @loan.item_id %>
</p>

<p>
  <strong>Borrower:</strong>
  <%= @loan.borrower_id %>
</p>

<p>
  <strong>Loaner:</strong>
  <%= @loan.loaner_id %>
</p>

<p>
  <strong>Approved:</strong>
  <%= @loan.approved %>
</p>

<p>
  <strong>Reserved start:</strong>
  <%= @loan.reserved_start %>
</p>

<p>
  <strong>Reserved end:</strong>
  <%= @loan.reserved_end %>
</p>

<%= link_to 'Edit', edit_loan_path(@loan) %> |
<%= link_to 'Back', loans_path %>